Update app to application set
hoprnet/ct-applications pull request #8
Opened 2023-08-29 07:00 UTC by sitilge

Update app to application set.

2023-08-29 08:02 UTC, jeandemeusy commented
How does each netwatcher instance receive a different `API_HOST` and `API_KEY` as environment variable ?

2023-08-29 09:44 UTC, jeandemeusy approved these changes

2023-08-29 10:05 UTC, ausias-armesto commented
> @jeandemeusy yes. There has to be a secret for each netwatcher called `netwatcher-*`.

Why the secrets are not created in this PR, the feature should be functional

2023-08-29 10:08 UTC, ausias-armesto commented
> > @jeandemeusy yes. There has to be a secret for each netwatcher called `netwatcher-*`.
> 
> Why the secrets are not created in this PR, the feature should be functional

Now I understand that the nodes are still not created. I will create the node for staging. This Application set should put in staging only, as in production we don't have the nodes either.

2023-08-30 11:24 UTC, ausias-armesto requested changes

2023-08-30 11:24 UTC, ausias-armesto commented on staging/netwatcher/application-set.yaml
> +      namespace: production
Is this namespece correct?

2023-08-30 11:24 UTC, ausias-armesto commented on staging/netwatcher/application-set.yaml
> +      namespace: production
Same here? Typo?

2023-08-30 11:24 UTC, ausias-armesto commented on staging/netwatcher/application-set.yaml
> +  namespace: production
and here

2023-08-30 11:28 UTC, ausias-armesto approved these changes

2023-08-30 11:36 UTC, merged